#ifndef INVENTARIO_H
#define INVENTARIO_H
#include "Nodo_listas.h"


//LEER ARCHIVO MATERIALES
//TIPO DATA HOLDER (NO TIENE PUNTEROS A CLASES/OBJETOS)
//SE VA A PODER CAMBIAR CANTIDADES
//INICIALIZAR CON TODAS LAS CANTIDADES EN 0 E IR SUMANDOLE A A CADA UNO.


class Inventario {
    int cantidad_elementos;


};


#endif //INVENTARIO_INVENTARIO_H
