#ifndef TP_3_ANDYPOLIS_BATALLA_OBELISCO_RAMA_REGISTRO_ED_E_INVENTARIO_INVENTARIO_H
#define TP_3_ANDYPOLIS_BATALLA_OBELISCO_RAMA_REGISTRO_ED_E_INVENTARIO_INVENTARIO_H
#include "Nodo_listas.h"


//LEER ARCHIVO MATERIALES
//TIPO DATA HOLDER (NO TIENE PUNTEROS A CLASES/OBJETOS)
//SE VA A PODER CAMBIAR CANTIDADES
//INICIALIZAR CON TODAS LAS CANTIDADES EN 0 E IR SUMANDOLE A A CADA UNO.


class Inventario {
    int cantidad_elementos;


};


#endif //TP_3_ANDYPOLIS_BATALLA_OBELISCO_RAMA_REGISTRO_ED_E_INVENTARIO_INVENTARIO_H
